[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
slot_machine = "8cozexydPUo9jTBT7PRWVe5Qmi3bpkjgQuPo2ZaTKHus"
slot_machine_token = "ADT9mwnQipeQTidQ8KaCxCs8Gxp681QAQFVmBfPMgCdp"

[programs.devnet]
slot_machine_token = "ADT9mwnQipeQTidQ8KaCxCs8Gxp681QAQFVmBfPMgCdp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false
